// Mock data - Replace with actual data fetching
import Trend2 from "@/assets/images/trends/trend2.jpg";
import Trend1 from "@/assets/images/trends/trend1.png";
import Trend3 from "@/assets/images/trends/trend3.jpg";
import Trend5 from "@/assets/images/trends/trend5.jpg";
import Trend6 from "@/assets/images/trends/trend6.jpg";

export const trendsData = [
  {
    image: Trend1,
    views: 123,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
  {
    image: Trend2,
    views: 456,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
  {
    image: Trend3,
    views: 789,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
  {
    image: Trend5,
    views: 112,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
  {
    image: Trend6,
    views: 131,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
];

export const DeliveryMethods = [
  // {
  //   label: "Standard delivery",
  //   value: "standard",
  //   duration: "1-2 days",
  //   amount: 1350,
  // },
  {
    label: "Speedaf",
    value: "speedaf",
    duration: "1-2 days",
    amount: 3100,
    image: "/speedaf.jpg",
  },
  {
    label: "DHL",
    value: "dhl",
    duration: "1-2 days",
    amount: 3200,
    image: "/dhl.png",
  },
  {
    label: "Edomason",
    value: "edomason",
    duration: "1-2 days",
    amount: 3400,
  },
];

export const newArrivalItems = [
  {
    title: "Brown Leather Bag",
    vendor: "Jayscloset",
    image: "/products/bag2.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    id: "oibNCJN-MRKJMxcA3P1bO",
  },
  {
    title: "white sneakers",
    vendor: "JaysKixks",
    image: "/products/sneaker.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    backgroundColor: "#c9d7ad",
    id: "MCdk4KCvgeD-mDRjEALU_",
  },
  {
    title: "gold female watch",
    vendor: "GoldenArena",
    image: "/products/watch.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    backgroundColor: "#70c2cf",
    id: "1TgdC6HSkEX71zbeqpCN0",
  },
  {
    title: "gold necklace",
    vendor: "GoldenArena",
    image: "/products/necklace.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#7c7c7c",
    discount: 30,
    id: "ciQoHqpfjVwlN2xAhG8Ll",
  },
  {
    title: "Gold Leather Bag",
    vendor: "Spellzluxury",
    image: "/products/bag.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    id: "VkeMmzfCPKCAtzBWfE1FE",
  },
  {
    title: "premium denim jacket",
    vendor: "JustDenim",
    image: "/products/denim.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    backgroundColor: "#c9d7ad",
    id: "RaNZfzLn0YWS18UnXrD7U",
  },
];

export const getNewArrivalItems = async () => {
  return [
    {
      title: "Brown Leather Bag",
      vendor: "Jayscloset",
      image: "/products/bag2.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      id: "oibNCJN-MRKJMxcA3P1bO",
    },
    {
      title: "white sneakers",
      vendor: "JaysKixks",
      image: "/products/sneaker.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#c9d7ad",
      id: "MCdk4KCvgeD-mDRjEALU_",
    },
    {
      title: "gold female watch",
      vendor: "GoldenArena",
      image: "/products/watch.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#70c2cf",
      id: "1TgdC6HSkEX71zbeqpCN0",
    },
    {
      title: "gold necklace",
      vendor: "GoldenArena",
      image: "/products/necklace.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#7c7c7c",
      discount: 30,
      id: "ciQoHqpfjVwlN2xAhG8Ll",
    },
    {
      title: "Gold Leather Bag",
      vendor: "Spellzluxury",
      image: "/products/bag.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      id: "VkeMmzfCPKCAtzBWfE1FE",
    },
    {
      title: "premium denim jacket",
      vendor: "JustDenim",
      image: "/products/denim.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#c9d7ad",
      id: "RaNZfzLn0YWS18UnXrD7U",
    },
  ];
};

export const getTrendingItems = async () => {
  return [
    {
      title: "Brown Leather Bag",
      vendor: "Jayscloset",
      image: "/products/bag2.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      id: "oibNCJN-MRKJMxcA3P1bO",
    },
    {
      title: "white sneakers",
      vendor: "JaysKixks",
      image: "/products/sneaker.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#c9d7ad",
      id: "MCdk4KCvgeD-mDRjEALU_",
    },
    {
      title: "gold female watch",
      vendor: "GoldenArena",
      image: "/products/watch.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#70c2cf",
      rating: 12,
      id: "1TgdC6HSkEX71zbeqpCN0",
    },
    {
      title: "gold necklace",
      vendor: "GoldenArena",
      image: "/products/necklace.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#7c7c7c",
      discount: 30,
      rating: 12,
      id: "ciQoHqpfjVwlN2xAhG8Ll",
    },
    {
      title: "Gold Leather Bag",
      vendor: "Spellzluxury",
      image: "/products/bag.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      id: "VkeMmzfCPKCAtzBWfE1FE",
    },
    {
      title: "premium denim jacket",
      vendor: "JustDenim",
      image: "/products/denim.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#c9d7ad",
      id: "RaNZfzLn0YWS18UnXrD7U",
    },
    {
      title: "Orange Courage Tee",
      vendor: "Jayscloset",
      image: "/products/t-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#e1d6cd",
      rating: 12,
      id: "Ep9bZ82BVpkjUIDE74qCi",
    },
    {
      title: "Vertical Stripped Shirt",
      vendor: "Jayscloset",
      image: "/products/stripped-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#eea468",
      rating: 12,
      id: "61O7sdv1z6P1sZRLCvcao",
    },
    {
      title: "Checkered Shirt",
      vendor: "Jayscloset",
      image: "/products/checkers-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#eea468",
      rating: 12,
      id: "BryC4N9eNJBE04-eba55m",
    },
  ];
};

export const forYouItems = async () => {
  return [
    {
      title: "Street wear Hoodie",
      vendor: "Streetfitz",
      image: "/products/hoodei.png",
      originalPrice: 30000,
      currentPrice: 24000,
      id: "jIqr7R8op1Y4U7m6TpFAF",
    },
    {
      title: "Skinny Fit Jean",
      vendor: "Streetfitz",
      image: "/products/skinny-jean.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "5IdF96_CGCBLDEuQYW5ae",
    },
    {
      title: "Checkered Shirt",
      vendor: "GoldenArena",
      image: "/products/checkers-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "BryC4N9eNJBE04-eba55m",
    },
    {
      title: "Street wear Hoodie",
      vendor: "GoldenArena",
      image: "/products/street-wear.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#a9b699",
      id: "MXwB6Pwk7r5lmrf_ahJUb",
    },
    {
      title: "Blue Washed Jorts",
      vendor: "streetfitz",
      image: "/products/blue-shorts.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "2EaKo6hzJN7tZjZAoDPTH",
    },
    {
      title: "Cotton Shirt",
      vendor: "JustDenim",
      image: "/products/cotton-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#fcd5b6",
      id: "gDoYgDVLoSR_no7tQgqOC",
    },
    {
      title: "Street wear Hoodie",
      vendor: "Jayscloset",
      image: "/products/street-jean.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "yKwHfBpjZx9zyZcP3bUXh",
    },
  ];
};

export const getAllProducts = [
  {
    title: "Gold Leather Bag",
    vendor: "Spellzluxury",
    image: "/products/bag.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    rating: 12,
    id: "VkeMmzfCPKCAtzBWfE1FE",
  },
  {
    title: "gold female watch",
    vendor: "GoldenArena",
    image: "/products/watch.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    backgroundColor: "#70c2cf",
    id: "1TgdC6HSkEX71zbeqpCN0",
  },
  {
    title: "Men’s Corporate Shoe",
    vendor: "Jayscloset",
    image: "/products/coperate-shoe.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    backgroundColor: "#70c2cf",
    rating: 12,
    id: "1TgdC6HSkEX71fbeqpCN0",
  },
  {
    title: "Alte Skirt",
    vendor: "GoldenArena",
    image: "/products/alte-skirt.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#7c7c7c",
    imgTagText: "-30%",
    rating: 12,
    id: "ciQoHqpfjVwlN2xAhG8Ll",
  },
  {
    title: "Corporate Heels",
    vendor: "Spellzluxury",
    image: "/products/heels.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    rating: 12,
    id: "Vk0MmzfCPKCAtzBWfE1FE",
  },
  {
    title: "Men’s Brown Corporate Shoe",
    vendor: "JustDenim",
    image: "/products/brown-shoe.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    rating: 12,
    backgroundColor: "#c9d7ad",
    id: "RaNZfzLn0wWS18UnXrD7U",
  },
  {
    title: "Unisex Leather Jacket",
    vendor: "Jayscloset",
    image: "/products/jacket.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    backgroundColor: "#e1d6cd",
    rating: 12,
    id: "Ep8bZ82BVpkjUIDE74qCi",
  },
  {
    title: "Stripped Polo",
    vendor: "GoldenArena",
    image: "/products/street-wear.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#a9b699",
    id: "MXwB6Pwk7r5lmrf_ahJUb",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Cotton Shirt",
    vendor: "JustDenim",
    image: "/products/cotton-shirt.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#fcd5b6",
    id: "gDoYgDVLoSR_no7tQgqOC",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Checkered Shirt",
    vendor: "GoldenArena",
    image: "/products/checkers-shirt.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#e1d6cd",
    id: "BryC4N9eNJBE04-eba55m",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Blue Washed Jorts",
    vendor: "streetfitz",
    image: "/products/blue-shorts.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#e1d6cd",
    id: "2EaKo6hzJN7tZjZAoDPTH",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Skinny Fit Jean",
    vendor: "Streetfitz",
    image: "/products/skinny-jean.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#e1d6cd",
    id: "5IdF96_CGCBLDEuQYW5ae",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Street wear Hoodie",
    vendor: "Streetfitz",
    image: "/products/hoodei.png",
    originalPrice: 30000,
    currentPrice: 24000,
    id: "jIqr7R8op1Y4U7m6TpFAF",
    rating: 12,
    imgTagText: "-30%",
  },
];

export const getAllItems = async () => {
  return [
    {
      title: "Gold Leather Bag",
      vendor: "Spellzluxury",
      image: "/products/bag.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      rating: 12,
      id: "VkeMmzfCPKCAtzBWfE1FE",
    },
    {
      title: "gold female watch",
      vendor: "GoldenArena",
      image: "/products/watch.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      backgroundColor: "#70c2cf",
      id: "1TgdC6HSkEX71zbeqpCN0",
    },
    {
      title: "Men’s Corporate Shoe",
      vendor: "Jayscloset",
      image: "/products/coperate-shoe.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      backgroundColor: "#70c2cf",
      rating: 12,
      id: "1TgdC6HSkEX71fbeqpCN0",
    },
    {
      title: "Alte Skirt",
      vendor: "GoldenArena",
      image: "/products/alte-skirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#7c7c7c",
      imgTagText: "-30%",
      rating: 12,
      id: "ciQoHqpfjVwlN2xAhG8Ll",
    },
    {
      title: "Corporate Heels",
      vendor: "Spellzluxury",
      image: "/products/heels.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      rating: 12,
      id: "Vk0MmzfCPKCAtzBWfE1FE",
    },
    {
      title: "Men’s Brown Corporate Shoe",
      vendor: "JustDenim",
      image: "/products/brown-shoe.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      rating: 12,
      backgroundColor: "#c9d7ad",
      id: "RaNZfzLn0wWS18UnXrD7U",
    },
    {
      title: "Unisex Leather Jacket",
      vendor: "Jayscloset",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      backgroundColor: "#e1d6cd",
      rating: 12,
      id: "Ep8bZ82BVpkjUIDE74qCi",
    },
    {
      title: "Stripped Polo",
      vendor: "GoldenArena",
      image: "/products/street-wear.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#a9b699",
      id: "MXwB6Pwk7r5lmrf_ahJUb",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Cotton Shirt",
      vendor: "JustDenim",
      image: "/products/cotton-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#fcd5b6",
      id: "gDoYgDVLoSR_no7tQgqOC",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Checkered Shirt",
      vendor: "GoldenArena",
      image: "/products/checkers-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "BryC4N9eNJBE04-eba55m",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Blue Washed Jorts",
      vendor: "streetfitz",
      image: "/products/blue-shorts.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "2EaKo6hzJN7tZjZAoDPTH",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Skinny Fit Jean",
      vendor: "Streetfitz",
      image: "/products/skinny-jean.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "5IdF96_CGCBLDEuQYW5ae",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Street wear Hoodie",
      vendor: "Streetfitz",
      image: "/products/hoodei.png",
      originalPrice: 30000,
      currentPrice: 24000,
      id: "jIqr7R8op1Y4U7m6TpFAF",
      rating: 12,
      imgTagText: "-30%",
    },
  ];
};

export const getWishlistItems = async () => {
  return [
    {
      id: "1",
      title: "Gold Wristwatch",
      vendor: "jayscloset",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#E5D5C8",
    },
    {
      id: "2",
      title: "Black n Orange",
      vendor: "jayscloset",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#C8D5BE",
    },
    {
      id: "3",
      title: "Brown Hoodie",
      vendor: "jayscloset",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#E5C8B8",
    },
  ];
};

export const getCartItems = async () => {
  return [
    {
      id: "1",
      title: "Vertical Stripped Shirt",
      vendor: "Jayscloset",
      image: "/products/jacket.png",
      price: 24000,
      size: "XXL",
      color: "#4A7C59",
      quantity: 1,
    },
    {
      id: "2",
      title: "Vertical Stripped Shirt",
      vendor: "Jayscloset",
      image: "/products/jacket.png",
      price: 24000,
      size: "XXL",
      color: "#4A7C59",
      quantity: 1,
    },
    {
      id: "3",
      title: "Vertical Stripped Shirt",
      vendor: "Jayscloset",
      image: "/products/jacket.png",
      price: 24000,
      size: "XXL",
      color: "#4A7C59",
      quantity: 1,
    },
  ];
};

export const getSuggestedProducts = async () => {
  return [
    {
      id: "s1",
      title: "Street wear Hoodie",
      vendor: "streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#E5C8B8",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s2",
      title: "Skinny Fit Jean",
      vendor: "streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#C8D5E5",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s3",
      title: "Checkered Shirt",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#E5D5E8",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s4",
      title: "Street wear Hoodie",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#C8D5BE",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s5",
      title: "Blue Washed Jorts",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#E5E5E5",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s6",
      title: "Cotton Shirt",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#F5D5C8",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s7",
      title: "Street wear Hoodie",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#C8C8C8",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
  ];
};

export const getUserAddresses = async () => {
  return [];
};
