// Mock data - Replace with actual data fetching
import Trend2 from "@/assets/images/trends/trend2.jpg";
import Trend1 from "@/assets/images/trends/trend1.png";
import Trend3 from "@/assets/images/trends/trend3.jpg";
import Trend5 from "@/assets/images/trends/trend5.jpg";
import Trend6 from "@/assets/images/trends/trend6.jpg";
import avatar1 from "@/assets/images/avatar/avatar1.png";
import avatar2 from "@/assets/images/avatar/avatar2.png";
import avatar3 from "@/assets/images/avatar/avatar3.png";
import avatar4 from "@/assets/images/avatar/avatar4.png";
import avatar5 from "@/assets/images/avatar/avatar5.png";
import avatar6 from "@/assets/images/avatar/avatar6.png";
import avatar7 from "@/assets/images/avatar/avatar7.png";

export const statusOptions = [
  { value: "all", label: "All" },
  { value: "pending", label: "Pending Payment" },
  { value: "processing", label: "Processing Order" },
  { value: "shipped", label: "Shipped" },
  { value: "delivered", label: "Delivered" },
  { value: "cancelled", label: "Cancelled" },
];

export const periodOptions = [
  { value: "all-time", label: "All Time" },
  { value: "last-7-days", label: "Last 7 Days" },
  { value: "last-30-days", label: "Last 30 Days" },
  { value: "last-90-days", label: "Last 90 Days" },
  { value: "this-year", label: "This Year" },
];

export const ordersData: Order[] = [
  {
    name: "Vertical Stripped Shirt",
    image: "/products/stripped-shirt.png",
    price: 79000,
    backgroundColor: "#EEA468",
    selectedColor: "#597858",
    size: "xxl",
    quantity: "X3",
    orderId: "PEN12345",
    status: "pending",
    colorName: "green",
    date: "2025-11-08T10:00:00.000Z",
  },
  {
    name: "Premium Denim Jacket",
    image: "/products/denim.png",
    price: 125000,
    backgroundColor: "#CDE49F",
    selectedColor: "#0088FF",
    size: "xl",
    quantity: "X5",
    orderId: "PEN12346",
    status: "processing",
    colorName: "blue",
    date: "2025-11-05T10:00:00.000Z",
  },
  {
    name: "Men’s Corporate shoes",
    image: "/products/brown-shoe.png",
    price: 95000,
    backgroundColor: "#A1A1A1",
    selectedColor: "#AC7F5E",
    size: "44",
    quantity: "X2",
    orderId: "PEN12347",
    status: "shipped",
    colorName: "brown",
    date: "2025-11-01T10:00:00.000Z",
  },
  {
    name: "Orange Courage Tee",
    image: "/products/t-shirt.png",
    price: 240000,
    backgroundColor: "#F0E1D5",
    selectedColor: "#FF8D28",
    size: "xl",
    quantity: "X4",
    orderId: "PEN12348",
    status: "delivered",
    colorName: "orange",
    date: "2025-10-25T10:00:00.000Z",
  },
  {
    name: "Unisex Gold Chain",
    image: "/products/necklace.png",
    price: 550000,
    backgroundColor: "#03435F",
    selectedColor: "#FFCC00",
    size: "23",
    quantity: "X2",
    orderId: "PEN12349",
    status: "cancelled",
    colorName: "gold",
    date: "2025-10-15T10:00:00.000Z",
  },
  {
    name: "Corporate Heels",
    image: "/products/heels.png",
    price: 32000,
    backgroundColor: "#F5AFCB",
    selectedColor: "#ECCBB3",
    colorName: "beige",
    size: "41",
    quantity: "X1",
    orderId: "PEN12350",
    status: "pending",
    date: "2025-10-01T10:00:00.000Z",
  },
];

export const mockConversations = [
  {
    id: "1",
    name: "Jane Doe",
    username: "@jd1999__",
    avatar: avatar1,
    lastMessage:
      "Hello, Any update on my order, i ought to have received it by now",
    lastMessageTime: "8:10",
    unreadCount: 3,
    isOnline: true,
  },
  {
    id: "2",
    name: "Jayscloset",
    username: "@jayscloset",
    avatar: avatar2,
    lastMessage: "Hi, is my order still on the way?",
    lastMessageTime: "8:10",
    unreadCount: 3,
    isOnline: true,
  },
  {
    id: "3",
    name: "Spellz",
    username: "@spellz",
    avatar: avatar3,
    lastMessage: "I want to make some enquiries about a product in your shop",
    lastMessageTime: "8:10",
    unreadCount: 3,
    isOnline: true,
  },
  {
    id: "4",
    name: "Jane Doe",
    username: "@jane99",
    avatar: avatar4,
    lastMessage: "Hello, Any update on my order, i ought t......",
    lastMessageTime: "8:10",
    unreadCount: 3,
    isOnline: true,
  },
  {
    id: "5",
    name: "Jane Doe",
    username: "@janed",
    avatar: avatar5,
    lastMessage: "Hello, Any update on my order, i ought t......",
    lastMessageTime: "8:10",
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: "6",
    name: "Jane Doe",
    username: "@jd2000",
    avatar: avatar6,
    lastMessage: "Hello, Any update on my order, i ought t......",
    lastMessageTime: "8:10",
    unreadCount: 3,
    isOnline: false,
  },
  {
    id: "7",
    name: "Jane Doe",
    username: "@janedoe99",
    avatar: avatar7,
    lastMessage: "Hello, Any update on my order, i ought t......",
    lastMessageTime: "8:10",
    unreadCount: 0,
    isOnline: false,
  },
];

export function getMessagesById(id: string): ChatMessage[] {
  if (id === "1") {
    return [
      {
        id: "m1",
        content:
          "Hello, Any update on my order, i ought to have received it by now",
        timestamp: "8:10",
        senderId: "1",
        senderName: "Jane Doe",
        senderAvatar: "/avatars/jane1.jpg",
        type: "text",
        isOwn: false,
      },
      {
        id: "m2",
        content:
          "Sorry for the inconvenience. Your order has been shipped, it is in transit",
        timestamp: "8:10",
        senderId: "current",
        senderName: "You",
        type: "text",
        isOwn: true,
      },
      {
        id: "m3",
        content: "Can I change the color?",
        timestamp: "8:10",
        senderId: "1",
        senderName: "Jane Doe",
        senderAvatar: "/avatars/jane1.jpg",
        type: "text",
        isOwn: false,
      },
      {
        id: "m4",
        content: "",
        timestamp: "8:10",
        senderId: "current",
        senderName: "You",
        type: "image",
        imageUrl: "/products/cotton-shirt.png",
        imageCaption: "This is how it looks",
        isOwn: true,
      },
    ];
  }
  return [];
}

export async function getMessages(
  conversationId: string
): Promise<ChatMessage[]> {
  // Simulate API call
  if (conversationId === "1") {
    return [
      {
        id: "m1",
        content:
          "Hello, Any update on my order, i ought to have received it by now",
        timestamp: "8:10",
        senderId: "1",
        senderName: "Jane Doe",
        senderAvatar: "/avatars/jane1.jpg",
        type: "text",
        isOwn: false,
      },
      {
        id: "m2",
        content:
          "Sorry for the inconvenience. Your order has been shipped, it is in transit",
        timestamp: "8:10",
        senderId: "current",
        senderName: "You",
        type: "text",
        isOwn: true,
      },
      {
        id: "m3",
        content: "Can I change the color?",
        timestamp: "8:10",
        senderId: "1",
        senderName: "Jane Doe",
        senderAvatar: "/avatars/jane1.jpg",
        type: "text",
        isOwn: false,
      },
      {
        id: "m4",
        content: "",
        timestamp: "8:10",
        senderId: "current",
        senderName: "You",
        type: "image",
        imageUrl: "/products/cotton-shirt.png",
        imageCaption: "This is how it looks",
        isOwn: true,
      },
    ];
  }
  return [];
}

export async function getConversations(): Promise<Conversation[]> {
  // This would be replaced with actual API call
  return [
    {
      id: "1",
      name: "Jane Doe",
      username: "@jd1999__",
      avatar: avatar1,
      lastMessage:
        "Hello, Any update on my order, i ought to have received it by now",
      lastMessageTime: "8:10",
      unreadCount: 3,
      isOnline: true,
    },
    {
      id: "2",
      name: "Jayscloset",
      username: "@jayscloset",
      avatar: avatar2,
      lastMessage: "Hi, is my order still on the way?",
      lastMessageTime: "8:10",
      unreadCount: 3,
      isOnline: true,
    },
    {
      id: "3",
      name: "Spellz",
      username: "@spellz",
      avatar: avatar3,
      lastMessage: "I want to make some enquiries about a product in your shop",
      lastMessageTime: "8:10",
      unreadCount: 3,
      isOnline: true,
    },
    {
      id: "4",
      name: "Jane Doe",
      username: "@jane99",
      avatar: avatar4,
      lastMessage: "Hello, Any update on my order, i ought t......",
      lastMessageTime: "8:10",
      unreadCount: 3,
      isOnline: true,
    },
    {
      id: "5",
      name: "Jane Doe",
      username: "@janed",
      avatar: avatar5,
      lastMessage: "Hello, Any update on my order, i ought t......",
      lastMessageTime: "8:10",
      unreadCount: 0,
      isOnline: true,
    },
    {
      id: "6",
      name: "Jane Doe",
      username: "@jd2000",
      avatar: avatar6,
      lastMessage: "Hello, Any update on my order, i ought t......",
      lastMessageTime: "8:10",
      unreadCount: 3,
      isOnline: false,
    },
    {
      id: "7",
      name: "Jane Doe",
      username: "@janedoe99",
      avatar: avatar7,
      lastMessage: "Hello, Any update on my order, i ought t......",
      lastMessageTime: "8:10",
      unreadCount: 0,
      isOnline: false,
    },
  ];
}

export const trendsData = [
  {
    image: Trend1,
    views: 123,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
  {
    image: Trend2,
    views: 456,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
  {
    image: Trend3,
    views: 789,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
  {
    image: Trend5,
    views: 112,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
  {
    image: Trend6,
    views: 131,
    text: "Lorem ipsum dolor sit amet, Lorem ipsum dolor",
  },
];

export const DeliveryMethods = [
  // {
  //   label: "Standard delivery",
  //   value: "standard",
  //   duration: "1-2 days",
  //   amount: 1350,
  // },
  {
    label: "Speedaf",
    value: "speedaf",
    duration: "1-2 days",
    amount: 3100,
    image: "/speedaf.jpg",
  },
  {
    label: "DHL",
    value: "dhl",
    duration: "1-2 days",
    amount: 3200,
    image: "/dhl.png",
  },
  {
    label: "Edomason",
    value: "edomason",
    duration: "1-2 days",
    amount: 3400,
  },
];

export const newArrivalItems = [
  {
    title: "Brown Leather Bag",
    vendor: "Jayscloset",
    image: "/products/bag2.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    id: "oibNCJN-MRKJMxcA3P1bO",
  },
  {
    title: "white sneakers",
    vendor: "JaysKixks",
    image: "/products/sneaker.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    backgroundColor: "#c9d7ad",
    id: "MCdk4KCvgeD-mDRjEALU_",
  },
  {
    title: "gold female watch",
    vendor: "GoldenArena",
    image: "/products/watch.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    backgroundColor: "#70c2cf",
    id: "1TgdC6HSkEX71zbeqpCN0",
  },
  {
    title: "gold necklace",
    vendor: "GoldenArena",
    image: "/products/necklace.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#7c7c7c",
    discount: 30,
    id: "ciQoHqpfjVwlN2xAhG8Ll",
  },
  {
    title: "Gold Leather Bag",
    vendor: "Spellzluxury",
    image: "/products/bag.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    id: "VkeMmzfCPKCAtzBWfE1FE",
  },
  {
    title: "premium denim jacket",
    vendor: "JustDenim",
    image: "/products/denim.png",
    originalPrice: 30000,
    currentPrice: 24000,
    discount: 30,
    backgroundColor: "#c9d7ad",
    id: "RaNZfzLn0YWS18UnXrD7U",
  },
];

export const getNewArrivalItems = async () => {
  return [
    {
      title: "Brown Leather Bag",
      vendor: "Jayscloset",
      image: "/products/bag2.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      id: "oibNCJN-MRKJMxcA3P1bO",
    },
    {
      title: "white sneakers",
      vendor: "JaysKixks",
      image: "/products/sneaker.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#c9d7ad",
      id: "MCdk4KCvgeD-mDRjEALU_",
    },
    {
      title: "gold female watch",
      vendor: "GoldenArena",
      image: "/products/watch.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#70c2cf",
      id: "1TgdC6HSkEX71zbeqpCN0",
    },
    {
      title: "gold necklace",
      vendor: "GoldenArena",
      image: "/products/necklace.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#7c7c7c",
      discount: 30,
      id: "ciQoHqpfjVwlN2xAhG8Ll",
    },
    {
      title: "Gold Leather Bag",
      vendor: "Spellzluxury",
      image: "/products/bag.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      id: "VkeMmzfCPKCAtzBWfE1FE",
    },
    {
      title: "premium denim jacket",
      vendor: "JustDenim",
      image: "/products/denim.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#c9d7ad",
      id: "RaNZfzLn0YWS18UnXrD7U",
    },
  ];
};

export const getTrendingItems = async () => {
  return [
    {
      title: "Brown Leather Bag",
      vendor: "Jayscloset",
      image: "/products/bag2.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      id: "oibNCJN-MRKJMxcA3P1bO",
    },
    {
      title: "white sneakers",
      vendor: "JaysKixks",
      image: "/products/sneaker.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#c9d7ad",
      id: "MCdk4KCvgeD-mDRjEALU_",
    },
    {
      title: "gold female watch",
      vendor: "GoldenArena",
      image: "/products/watch.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#70c2cf",
      rating: 12,
      id: "1TgdC6HSkEX71zbeqpCN0",
    },
    {
      title: "gold necklace",
      vendor: "GoldenArena",
      image: "/products/necklace.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#7c7c7c",
      discount: 30,
      rating: 12,
      id: "ciQoHqpfjVwlN2xAhG8Ll",
    },
    {
      title: "Gold Leather Bag",
      vendor: "Spellzluxury",
      image: "/products/bag.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      id: "VkeMmzfCPKCAtzBWfE1FE",
    },
    {
      title: "premium denim jacket",
      vendor: "JustDenim",
      image: "/products/denim.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#c9d7ad",
      id: "RaNZfzLn0YWS18UnXrD7U",
    },
    {
      title: "Orange Courage Tee",
      vendor: "Jayscloset",
      image: "/products/t-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#e1d6cd",
      rating: 12,
      id: "Ep9bZ82BVpkjUIDE74qCi",
    },
    {
      title: "Vertical Stripped Shirt",
      vendor: "Jayscloset",
      image: "/products/stripped-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#eea468",
      rating: 12,
      id: "61O7sdv1z6P1sZRLCvcao",
    },
    {
      title: "Checkered Shirt",
      vendor: "Jayscloset",
      image: "/products/checkers-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      backgroundColor: "#eea468",
      rating: 12,
      id: "BryC4N9eNJBE04-eba55m",
    },
  ];
};

export const forYouItems = async () => {
  return [
    {
      title: "Street wear Hoodie",
      vendor: "Streetfitz",
      image: "/products/hoodei.png",
      originalPrice: 30000,
      currentPrice: 24000,
      id: "jIqr7R8op1Y4U7m6TpFAF",
    },
    {
      title: "Skinny Fit Jean",
      vendor: "Streetfitz",
      image: "/products/skinny-jean.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "5IdF96_CGCBLDEuQYW5ae",
    },
    {
      title: "Checkered Shirt",
      vendor: "GoldenArena",
      image: "/products/checkers-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "BryC4N9eNJBE04-eba55m",
    },
    {
      title: "Street wear Hoodie",
      vendor: "GoldenArena",
      image: "/products/street-wear.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#a9b699",
      id: "MXwB6Pwk7r5lmrf_ahJUb",
    },
    {
      title: "Blue Washed Jorts",
      vendor: "streetfitz",
      image: "/products/blue-shorts.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "2EaKo6hzJN7tZjZAoDPTH",
    },
    {
      title: "Cotton Shirt",
      vendor: "JustDenim",
      image: "/products/cotton-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#fcd5b6",
      id: "gDoYgDVLoSR_no7tQgqOC",
    },
    {
      title: "Street wear Hoodie",
      vendor: "Jayscloset",
      image: "/products/street-jean.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "yKwHfBpjZx9zyZcP3bUXh",
    },
  ];
};

export const getAllProducts = [
  {
    title: "Gold Leather Bag",
    vendor: "Spellzluxury",
    image: "/products/bag.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    rating: 12,
    id: "VkeMmzfCPKCAtzBWfE1FE",
  },
  {
    title: "gold female watch",
    vendor: "GoldenArena",
    image: "/products/watch.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    backgroundColor: "#70c2cf",
    id: "1TgdC6HSkEX71zbeqpCN0",
  },
  {
    title: "Men’s Corporate Shoe",
    vendor: "Jayscloset",
    image: "/products/coperate-shoe.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    backgroundColor: "#70c2cf",
    rating: 12,
    id: "1TgdC6HSkEX71fbeqpCN0",
  },
  {
    title: "Alte Skirt",
    vendor: "GoldenArena",
    image: "/products/alte-skirt.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#7c7c7c",
    imgTagText: "-30%",
    rating: 12,
    id: "ciQoHqpfjVwlN2xAhG8Ll",
  },
  {
    title: "Corporate Heels",
    vendor: "Spellzluxury",
    image: "/products/heels.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    rating: 12,
    id: "Vk0MmzfCPKCAtzBWfE1FE",
  },
  {
    title: "Men’s Brown Corporate Shoe",
    vendor: "JustDenim",
    image: "/products/brown-shoe.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    rating: 12,
    backgroundColor: "#c9d7ad",
    id: "RaNZfzLn0wWS18UnXrD7U",
  },
  {
    title: "Unisex Leather Jacket",
    vendor: "Jayscloset",
    image: "/products/jacket.png",
    originalPrice: 30000,
    currentPrice: 24000,
    imgTagText: "-30%",
    backgroundColor: "#e1d6cd",
    rating: 12,
    id: "Ep8bZ82BVpkjUIDE74qCi",
  },
  {
    title: "Stripped Polo",
    vendor: "GoldenArena",
    image: "/products/street-wear.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#a9b699",
    id: "MXwB6Pwk7r5lmrf_ahJUb",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Cotton Shirt",
    vendor: "JustDenim",
    image: "/products/cotton-shirt.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#fcd5b6",
    id: "gDoYgDVLoSR_no7tQgqOC",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Checkered Shirt",
    vendor: "GoldenArena",
    image: "/products/checkers-shirt.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#e1d6cd",
    id: "BryC4N9eNJBE04-eba55m",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Blue Washed Jorts",
    vendor: "streetfitz",
    image: "/products/blue-shorts.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#e1d6cd",
    id: "2EaKo6hzJN7tZjZAoDPTH",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Skinny Fit Jean",
    vendor: "Streetfitz",
    image: "/products/skinny-jean.png",
    originalPrice: 30000,
    currentPrice: 24000,
    backgroundColor: "#e1d6cd",
    id: "5IdF96_CGCBLDEuQYW5ae",
    rating: 12,
    imgTagText: "-30%",
  },
  {
    title: "Street wear Hoodie",
    vendor: "Streetfitz",
    image: "/products/hoodei.png",
    originalPrice: 30000,
    currentPrice: 24000,
    id: "jIqr7R8op1Y4U7m6TpFAF",
    rating: 12,
    imgTagText: "-30%",
  },
];

export const getAllItems = async () => {
  return [
    {
      title: "Gold Leather Bag",
      vendor: "Spellzluxury",
      image: "/products/bag.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      rating: 12,
      id: "VkeMmzfCPKCAtzBWfE1FE",
    },
    {
      title: "gold female watch",
      vendor: "GoldenArena",
      image: "/products/watch.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      backgroundColor: "#70c2cf",
      id: "1TgdC6HSkEX71zbeqpCN0",
    },
    {
      title: "Men’s Corporate Shoe",
      vendor: "Jayscloset",
      image: "/products/coperate-shoe.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      backgroundColor: "#70c2cf",
      rating: 12,
      id: "1TgdC6HSkEX71fbeqpCN0",
    },
    {
      title: "Alte Skirt",
      vendor: "GoldenArena",
      image: "/products/alte-skirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#7c7c7c",
      imgTagText: "-30%",
      rating: 12,
      id: "ciQoHqpfjVwlN2xAhG8Ll",
    },
    {
      title: "Corporate Heels",
      vendor: "Spellzluxury",
      image: "/products/heels.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      rating: 12,
      id: "Vk0MmzfCPKCAtzBWfE1FE",
    },
    {
      title: "Men’s Brown Corporate Shoe",
      vendor: "JustDenim",
      image: "/products/brown-shoe.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      rating: 12,
      backgroundColor: "#c9d7ad",
      id: "RaNZfzLn0wWS18UnXrD7U",
    },
    {
      title: "Unisex Leather Jacket",
      vendor: "Jayscloset",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      imgTagText: "-30%",
      backgroundColor: "#e1d6cd",
      rating: 12,
      id: "Ep8bZ82BVpkjUIDE74qCi",
    },
    {
      title: "Stripped Polo",
      vendor: "GoldenArena",
      image: "/products/street-wear.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#a9b699",
      id: "MXwB6Pwk7r5lmrf_ahJUb",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Cotton Shirt",
      vendor: "JustDenim",
      image: "/products/cotton-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#fcd5b6",
      id: "gDoYgDVLoSR_no7tQgqOC",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Checkered Shirt",
      vendor: "GoldenArena",
      image: "/products/checkers-shirt.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "BryC4N9eNJBE04-eba55m",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Blue Washed Jorts",
      vendor: "streetfitz",
      image: "/products/blue-shorts.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "2EaKo6hzJN7tZjZAoDPTH",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Skinny Fit Jean",
      vendor: "Streetfitz",
      image: "/products/skinny-jean.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#e1d6cd",
      id: "5IdF96_CGCBLDEuQYW5ae",
      rating: 12,
      imgTagText: "-30%",
    },
    {
      title: "Street wear Hoodie",
      vendor: "Streetfitz",
      image: "/products/hoodei.png",
      originalPrice: 30000,
      currentPrice: 24000,
      id: "jIqr7R8op1Y4U7m6TpFAF",
      rating: 12,
      imgTagText: "-30%",
    },
  ];
};

export const getWishlistItems = async () => {
  return [
    {
      id: "1",
      title: "Gold Wristwatch",
      vendor: "jayscloset",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#E5D5C8",
    },
    {
      id: "2",
      title: "Black n Orange",
      vendor: "jayscloset",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#C8D5BE",
    },
    {
      id: "3",
      title: "Brown Hoodie",
      vendor: "jayscloset",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      discount: 30,
      rating: 12,
      backgroundColor: "#E5C8B8",
    },
  ];
};

export const getCartItems = async () => {
  return [
    {
      id: "1",
      title: "Vertical Stripped Shirt",
      vendor: "Jayscloset",
      image: "/products/jacket.png",
      price: 24000,
      size: "XXL",
      color: "#4A7C59",
      quantity: 1,
    },
    {
      id: "2",
      title: "Vertical Stripped Shirt",
      vendor: "Jayscloset",
      image: "/products/jacket.png",
      price: 24000,
      size: "XXL",
      color: "#4A7C59",
      quantity: 1,
    },
    {
      id: "3",
      title: "Vertical Stripped Shirt",
      vendor: "Jayscloset",
      image: "/products/jacket.png",
      price: 24000,
      size: "XXL",
      color: "#4A7C59",
      quantity: 1,
    },
  ];
};

export const getSuggestedProducts = async () => {
  return [
    {
      id: "s1",
      title: "Street wear Hoodie",
      vendor: "streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#E5C8B8",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s2",
      title: "Skinny Fit Jean",
      vendor: "streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#C8D5E5",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s3",
      title: "Checkered Shirt",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#E5D5E8",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s4",
      title: "Street wear Hoodie",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#C8D5BE",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s5",
      title: "Blue Washed Jorts",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#E5E5E5",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s6",
      title: "Cotton Shirt",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#F5D5C8",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
    {
      id: "s7",
      title: "Street wear Hoodie",
      vendor: "@streetfitz",
      image: "/products/jacket.png",
      originalPrice: 30000,
      currentPrice: 24000,
      backgroundColor: "#C8C8C8",
      suggestionReason: "Suggested for you",
      likedBy: [
        { avatar: "", name: "User 1" },
        { avatar: "", name: "User 2" },
        { avatar: "", name: "User 3" },
      ],
      additionalLikes: 32,
    },
  ];
};

export const getUserAddresses = async () => {
  return [];
};
